### ISSUE TITLE
Help request: centering

### ISSUE THREAD

**Issue by ghost** [callmenick/flexgrid.css#5]
Hello,

Thank you for your grid and work that you put into it.

I would like to ask for assistance, if you would, please. I am an amateur.

Below is a screenshot of a site's header where I would like everything to be centered, and further below is the code to this end.

![flexgrid](https://cloud.githubusercontent.com/assets/6915858/15971496/fe47e2e2-2f41-11e6-8a2b-46f82411f99b.png)

```
<header>

    <div class="Grid Grid--alignCenter">
        <div class="Grid-cell--auto">
            <a href="{{ site.url }}">Logo</a>
        </div>
        <div class="Grid Grid--alignCenter">
            <div class="Grid-cell--auto">
                <h1 class="site-title">{{ site.title }}</h1>
                <h2 class="site-description"></h2>
            </div>
        </div>
    </div>

    <div class="Grid">
        <div class="Grid-cell--auto">
            <nav class="site-nav">
                {% include navigation.html %}
            </nav>
        </div>
    </div>

</header>

```

I cannot figure out how to center the elements and asking for your assistance, please.

Thank you!

**Comment by devinmcinnis** [comment]
Not sure if I fully understood the question (it would be better if you hosted something on JSFiddle) but I added the `Grid--justifyCenter` class to both parent `<div>` elements. 

https://jsfiddle.net/yueaj2oy/

`justifyCenter` will align left-to-right. `alignCenter` will align top-to-bottom. 

Hope that helps :) Let me know if this solved your problem.

**Comment by ghost** [comment]
@devinmcinnis thank you very much for reply!

I have put the whole page on JSFiddle. If you would please take a look at it once more.

Without the included typography kit, everything is centered. But with the kit, site logo and, particularly, the title are off the center. I see no overlapping classes in Flexgrid and Gutenberg and would be grateful for your expert look at this.

Thank you :)

https://jsfiddle.net/yueaj2oy/3/

**Comment by ghost** [comment]
I have now figured out what was wrong. Thanks once again for your work and help :)
